name: Generate ASN database
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
    - uses: actions/checkout@v2

    - name: Update apt
      run: echo "deb [ arch=amd64 allow-insecure=yes trusted=yes ] https://perl-team.pages.debian.net/modules/packages/libmaxmind-db-writer-perl/ autobuilt main" >> /etc/apt/sources.list
    - name: Update apt
      run: apt-get update

    - name: Install deps
      run: apt-get install --no-install-recommends -y bgpdump curl libmaxmind-db-writer-perl --allow-unauthenticated

    - name: Generate database
      run: ./generator.sh

    - name: End
      run: ls -ltr

    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: output.mmdb
        path: output.mmdb
