name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
    - uses: actions/checkout@v2

    - name: Update apt
      run: apt-get update

    - name: Install deps
      run: apt-get install --no-install-recommends -y bgpdump

    - name: Generate database
      run: ./generator.sh

    - name: End
      run: ls -ltr

    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: output.mmdb
        path: output.mmdb
