name: Generate ASN database
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
    - uses: actions/checkout@v2

    - name: Show apt version
      run: apt-get -v

    - name: Update apt
      run: apt-get update

    - name: Install deps
      run: apt-get install --no-install-recommends -y bgpdump curl libmaxmind-db-writer-perl python3

    - name: Generate database using RIPE BGP dump and CAIDA AS names
      run: ./generator_ripe_caida.sh

    - name: End
      run: ls -ltr

    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: asn.mmdb
        path: asn.mmdb

    #- name: Upload binaries to release
    #  uses: svenstaro/upload-release-action@v2
    #  with:
    #    repo_token: ${{ secrets.GITHUB_TOKEN }}
    #    file: asn.mmdb
    #    asset_name: ${{ matrix.asset_name }}
    #    tag: ${{ github.ref }}
