name: Generate ASN database
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: "14 17 * * 3"

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
    - uses: actions/checkout@v2

    - name: Show apt version
      run: apt-get -v

    - name: Update apt
      run: apt-get update

    - name: Install deps
      run: apt-get install --no-install-recommends -y bgpdump ca-certificates curl libmaxmind-db-writer-perl python3 python3-gdbm python3-maxminddb

    - name: Generate database using RIPE BGP dump and CAIDA AS names
      run: ./generator_ripe_caida.sh

    - name: End
      run: ls -ltr

    - name: Verify the generated file
      run: ./smoketest.py

    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: asn.mmdb
        path: asn.mmdb
